# Generated by Django 4.2.11 on 2025-09-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='updeted_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='updeted_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='updeted_at',
            new_name='updated_at',
        ),
    ]
