# Generated by Django 4.2.11 on 2025-09-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_updeted_at_filmwork_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.URLField(blank=True, editable=False, verbose_name='file_path'),
        ),
    ]
