services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: theatre_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py createsuperuser --noinput ||
             true &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume: