# Generated by Django 4.2.11 on 2025-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_filmwork_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='film_work_id',
            new_name='film_work',
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='film_work_id',
            new_name='film_work',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='person_id',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='file_path',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='file_path'),
        ),
    ]
